# Generated by Django 5.2.7 on 2025-10-11 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название/идентификатор автомобиля', max_length=100)),
                ('make', models.CharField(blank=True, help_text='Производитель', max_length=50)),
                ('model', models.CharField(blank=True, help_text='Модель', max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Год выпуска', null=True)),
                ('fuel_type', models.CharField(blank=True, help_text='Тип топлива', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли автомобиль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(help_text='Дата заправки')),
                ('odometer', models.PositiveIntegerField(help_text='Показания одометра в км')),
                ('station_name', models.CharField(help_text='Название АЗС', max_length=100)),
                ('fuel_brand', models.CharField(help_text='Бренд топлива', max_length=50)),
                ('fuel_grade', models.CharField(help_text='Марка/октановое число топлива', max_length=20)),
                ('liters', models.DecimalField(decimal_places=2, help_text='Количество литров', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Общая стоимость', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Заметки', max_length=500)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, help_text='Цена за литр', max_digits=10, null=True)),
                ('distance_since_last', models.IntegerField(blank=True, help_text='Расстояние с предыдущей заправки (км)', null=True)),
                ('consumption_l_100km', models.DecimalField(blank=True, decimal_places=1, help_text='Расход л/100км', max_digits=5, null=True)),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=4, help_text='Стоимость за км', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='api.vehicle')),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['user', '-created_at'], name='api_vehicle_user_id_b89e89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', '-entry_date'], name='api_fuelent_vehicle_b0ebd3_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['user', '-entry_date'], name='api_fuelent_user_id_24c686_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', 'odometer'], name='api_fuelent_vehicle_e293ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelentry',
            unique_together={('vehicle', 'entry_date', 'odometer')},
        ),
    ]
