# Generated by Django 5.2.7 on 2025-10-11 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['user', 'entry_date'], name='api_fuelent_user_id_99a4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', 'entry_date'], name='api_fuelent_vehicle_9e71ab_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['user', 'entry_date', 'consumption_l_100km'], name='api_fuelent_user_id_3d5a0d_idx'),
        ),
    ]
