# Generated by Django 5.2.7 on 2025-10-12 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fuelentry_api_fuelent_user_id_99a4a8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['user', 'fuel_brand', 'consumption_l_100km'], name='api_fuelent_user_id_f02835_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['user', 'fuel_grade', 'consumption_l_100km'], name='api_fuelent_user_id_9e0131_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', 'fuel_brand', 'consumption_l_100km'], name='api_fuelent_vehicle_a085c5_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelentry',
            index=models.Index(fields=['vehicle', 'fuel_grade', 'consumption_l_100km'], name='api_fuelent_vehicle_561c75_idx'),
        ),
    ]
