# Generated by Django 5.2.7 on 2025-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_statistics_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='initial_odometer',
            field=models.PositiveIntegerField(default=0, help_text='Initial odometer reading in km'),
        ),
    ]
