# Generated by Django 5.2.7 on 2025-10-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price_precision',
            field=models.IntegerField(choices=[(2, '2 decimals'), (3, '3 decimals')], default=2),
        ),
    ]
